---
openapi: 3.0.3
info:
  title: <overriden by annotation. see Application class>
  description: Give access (CRUD) to every video games for the ATARI ST.
  contact:
    name: François-Xavier Robin
    url: https://www.fxjavadevblog.fr
    email: webmaster@fxjavadevblog.fr
  license:
    name: Apache 2.0
    url: https://www.fxjavadevblog.fr
  version: <overriden by annotation see Application class>
  x-data-atari: ST, STF, STFM, STE, MEGA ST, MEGA STE, FALCON
  x-data-protection: NONE

tags:
- name: Health and Metrics
  description: get metadada from the underlaying application.

paths:
  /health:
    get:
      tags:
      - Health and Metrics
      responses:
        "200":
          description: OK
  /metrics:
    get:
      tags:
      - Health and Metrics
      responses:
        "200":
          description: OK