---
openapi: 3.0.3
info:
  title: <overriden by annotation. see Application class>
  description: "Give access (CRUD) to every video games of the famous 90's computer : ATARI ST."
  contact:
    name: François-Xavier Robin
    url: https://www.fxjavadevblog.fr
    email: webmaster@fxjavadevblog.fr
  license:
    name: Apache 2.0
    url: https://www.fxjavadevblog.fr
  version: <overriden by annotation see Application class>
  x-data-atari: ST, STF, STFM, STE, MEGA ST, MEGA STE, FALCON
  x-data-protection: NONE

tags:
- name: Health and Metrics
  description: get metadada from the underlaying application.

paths:
  /health:
    get:
      tags:
      - Health and Metrics
      summary: Returns information (JSON) about the API and the backend resources health.
      produces: application/json
      responses:
        "200":
          description: OK   
          content:
            application/json:
              schema:
                type: Object        
        "500":
          description: The API is not ready.
        "404":
          description: There is no monitored API at this address.
            
  /metrics:
    get:
      tags:
      - Health and Metrics
      summary: Returns statistics (PLAIN TEXT) about the running API.
      produces: text/plain
      responses:
        "200":
           description: OK
           content:
            text/plain:
              schema:          
                type: String
              