---
openapi: 3.0.3
info:
  title: Simple API over video games catalog of ATARI ST
  description: Give read access to every video games for the ATARI ST
  contact:
    name: François-Xavier Robin
    url: https://www.fxjavadevblog.fr
    email: webmaster@fxjavadevblog.fr
  license:
    name: Apache 2.0
    url: https://www.fxjavadevblog.fr
  version: 1.0.0
  x-data-atari: ST, STF, STFM, STE, MEGA ST, MEGA STE, FALCON
  x-data-protection: NONE
